from think_bayes.cookie_function import cookie_function
from think_bayes.diachronic_cookie import DiachronicCookie
from think_bayes.mnm_table import MnMTable
from think_bayes.monty_hall_random_pick_table import MontyHallRandomPickTable
from think_bayes.monty_hall_always_b_table import MontyHallAlwaysBTable
